version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=oluwaseun
      - POSTGRES_DB=db213
  app:
    image: my-node-app
    ports:
      - "13000:3000"  # Corrected to ensure it's recognized as a list
